apiVersion: v1
kind: Secret
metadata:
  name: luk-auth-key-rsa-cm
  namespace: {{ .Values.namespace }}
data:
  key.rsa: >-
    TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFnZS9ZNjJodm0zNXArQit6QlpGc3MxNVN2NHZ5cEtjcWdRenhrRVdtL1FTSjNMR0lVMk5sbDludzluUXk0Z1lpS0d3aGZqQ1dQeG5VRFFISDVLcjVSTWc5aEc0SjloRWphcWNvK2p6dk5BUEUrRW9LQ1k5QVdad2ZvdW9zbzdjV2Q0UURMNVQwMjZkemFzemdjL2U2d3RkZ1F6cHR3d0hrQm5sRm9pWDh0aEV5bmRnYThPVmt1TkdRSy9pNWFnMXN0OVE5YUZEUUE3aGVTTjF6SjRqR1JadjIxNlRnWFc5T3BwaktzR0N3MEdreVZBZUdlcnZHL3B6MEtZTDdndmdGais2bitIWE1VMHZwaEV0NjlXZnd0Ylk4U0VYVmtKUjJ3RTY2WlQ2RDJuUkZHUkFFZFRJa0xLWERxRlJVd3U1WE8yVytJd2RJNE1Yc3JFcThNU1g2aVFJREFRQUIK
type: Opaque
