argocd_project:  "${project_name}"
app_namespace: "test"

namespace: luk-dev
# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


replicaCount: 1
host:
  name: luk-dev.lukoil-hrportal.ru
rtl_db:
  url: 192.168.56.122 
  port: 5432
env:
  RTL_PROFILE: prod
  RTL_KCLK_URL: https://uep-luk-auth.lukoil-hrportal.ru
  RTL_KCLK_REALM: lukoil
  RTL_KCLK_USER: api-service
  RTL_KCLK_PASS: 123
  RTL_KCLK_CLID: api-service-agent
  RTL_KCLK_CLSECRET: 24c9dcbb-4c2a-499c-a18b-fa25ed4a2fcc
  RTL_USE_MINIO: false
  RTL_USE_FILESYSTEM: true
  RTL_USE_WEBDAV: false
  RTL_MAIL_HOST: smtp.yandex.ru
  RTL_MAIL_PORT: 587
  RTL_MAIL_USER: mail-test-robot@yandex.ru
  RTL_MAIL_PASS: aqehonyswjhhbbsd
  RTL_MAIL_FROM: mail-test-robot@yandex.ru
  RTL_KCLK_AUTH_ENABLED: false
  RTL_MINIO_URL: http://minio-service.minio:9000
  RTL_MINIO_BUCKET: luk-dev
  RTL_MINIO_USER: minio_admin
  RTL_MINIO_PASS: fsfIggPaxv34SLYj1FJZ
  RTL_WEBDAV_URL:
  RTL_WEBDAV_USER:
  RTL_WEBDAV_PASS:
  RTL_SUR_URL: https://luk-dev.lukoil-hrportal.ru/rtl-api/authority
  RTL_DB_RTL_USER: qwe
  RTL_DB_RTL_PASS: qwe
  RTL_DB_RTL_URL: "jdbc:postgresql://{{ .Values.rtl_db.url }}:{{ .Values.rtl_db.port }}/rtl"
  RTL_ROOT_HOST_URL:
  DREMIO_URL: http://10.0.0.201:9047
  DREMIO_UI: http://10.0.0.201:9047
  RTL_BACKEND_ROSTALENT_URL: https://luk-dev.lukoil-hrportal.ru/rtl-api/rt-core
  RTL_BACKEND_AUTHORITY_URL: https://luk-dev.lukoil-hrportal.ru/rtl-api/authority
  RTL_BACKEND_MONITOR_URL: https://luk-dev.lukoil-hrportal.ru/rtl-api/monitor
  RTL_BACKEND_LEARNING_URL: https://luk-dev.lukoil-hrportal.ru/rtl-api/learning
  RTL_BACKEND_NOTIFY_URL: https://luk-dev.lukoil-hrportal.ru/rtl-api/notify
  RTL_DREMIOCONNECTOR_URL: https://luk-dev.lukoil-hrportal.ru/connector-1
  RTL_BACKEND_BP_URL: https://luk-dev.lukoil-hrportal.ru/rtl-api/bp
  RTL_BACKEND_QUIZ_URL: https://luk-dev.lukoil-hrportal.ru/rtl-api/quiz
  RTL_REPORT_DOWNLOAD_PAGE: https://luk-dev.lukoil-hrportal.ru/rtl-api/report-service/
  RTL_BACKEND_CAMUNDA_URL: https://luk-dev.lukoil-hrportal.ru/rtl-api/bp
  RTL_BACKEND_FILEUPLOAD_URL: https://luk-dev.lukoil-hrportal.ru/rtl-api/fileupload
  RTL_KAFKA_TOPIC: luk_dev
  RTL_KAFKA_URL: kafka-headless.kafka.svc.cluster.local:9092
  RTL_BACKEND_COMPETENCE_URL: https://luk-dev.lukoil-hrportal.ru/rtl-api/competence
  RTL_BACKEND_CONFIGURATION_URL: https://luk-dev.lukoil-hrportal.ru/rtl-api/configuration
  RTL_NOTIFICATION_URL: https://luk-dev.lukoil-hrportal.ru/rtl-api/main
####################################################

#         RTL CORE settings

####################################################
rtlcore:
  enabled: true
  replicas: 1
  name: rtl-rt-core
  version:
  image:
    repository: registry.gitlab.vktech.tools/b2b/hr/lukoil-hrportal/talent/backend/goodt-drive-rt-core/rtl-rt-core
    tag: 1663_develop
  values:
    RTL_DB_URL: rt-core
    JAVAOPTS: -Xms512m -Xmx8192m
    RTL_DB_USER: task_org_user
    RTL_DB_PASS: Lolkalol93
    RTL_DATA_BUS_HOST: http://localhost/RESTAdapter
    RTL_DATA_BUS_LOGIN: ESB_VCP
    RTL_DATA_BUS_PASSWORD: 11111
####################################################






image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""



service:
  type: ClusterIP
  port: 80
