lues.yaml
7.25 KiB
defaultImagePullPolicy: IfNotPresent
diagnosticMode: {}
deployments:
  nginx:
    replicas: 1
    containers:
      - name: "nginx"
        image: "nginx"
        imageTag: "latest"

