apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-vktech-secret
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIudmt0ZWNoLnRvb2xzIjp7InVzZXJuYW1lIjoiSWdvcllhbm9jaGtpbiIsInBhc3N3b3JkIjoiOWVzYVpMZkxISzI3eGNXeVJENGciLCJlbWFpbCI6ImkueWFub2Noa2luQHZrdGVhbS5ydSIsImF1dGgiOiJTV2R2Y2xsaGJtOWphR3RwYmpvNVpYTmhXa3htVEVoTE1qZDRZMWQ1VWtRMFp3PT0ifX19
type: kubernetes.io/dockerconfigjson
