apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rtlcore.name }}
  namespace: {{ .Values.namespace }}
  labels:
    environment: {{ .Values.namespace }}
    version: {{ .Values.rtlcore.image.tag  }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.rtlcore.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.rtlcore.name }}
        environment: {{ .Values.namespace }}
        version: {{ .Values.rtlcore.image.tag  }}
    spec:
      volumes:
        - name: luk-auth-key-rsa-cm
          secret:
            secretName: luk-auth-key-rsa-cm
      containers:    
        - name: {{ .Values.rtlcore.name }}
          image: "{{ .Values.rtlcore.image.repository }}:{{ .Values.rtlcore.image.tag }}"
          ports:
            - containerPort: 8071
              protocol: TCP
          env:
            - name: RTL_DB_USER
              value: {{ .Values.rtlcore.values.RTL_DB_USER }}
            - name: RTL_DB_PASS
              value: {{ .Values.rtlcore.values.RTL_DB_PASS }}
            - name: RTL_DB_URL
              value: jdbc:postgresql://{{ .Values.rtl_db.url }}:{{ .Values.rtl_db.port }}/rtl?currentSchema=rt_core               
            - name: RTL_PROFILE
              value: prod
            - name: RTL_ISSUER_URI 
              value: {{ .Values.env.RTL_KCLK_URL }}/auth/realms/{{ .Values.env.RTL_KCLK_REALM }}              
            - name: RTL_SUR_URL 
              value: {{ .Values.env.RTL_SUR_URL }}
            - name: RTL_BACKEND_MONITOR_URL
              value: {{ .Values.env.RTL_BACKEND_MONITOR_URL }}
            - name: RTL_BACKEND_LEARNING_URL
              value: {{ .Values.env.RTL_BACKEND_LEARNING_URL }}
            - name: RTL_BACKEND_FILEUPLOAD_URL
              value: {{ .Values.env.RTL_BACKEND_FILEUPLOAD_URL }}
            - name: RTL_NOTIFY_URL 
              value: {{ .Values.env.RTL_BACKEND_NOTIFY_URL }}                            
            - name: RTL_MINIO_URL 
              value: {{ .Values.env.RTL_MINIO_URL }}
            - name: RTL_MINIO_BUCKET
              value: {{ .Values.env.RTL_MINIO_BUCKET }}
            - name: RTL_MINIO_USER
              value: {{ .Values.env.RTL_MINIO_USER }}
            - name: RTL_MINIO_PASS
              value: {{ .Values.env.RTL_MINIO_PASS }}
            - name: JAVAOPTS
              value: '{{ .Values.rtlcore.values.JAVAOPTS }}'
            - name: RTL_DATA_BUS_HOST
              value: {{ .Values.rtlcore.values.RTL_DATA_BUS_HOST }}
            - name: RTL_DATA_BUS_LOGIN
              value: {{ .Values.rtlcore.values.RTL_DATA_BUS_LOGIN }}
            - name: RTL_DATA_BUS_PASSWORD
              value: '{{ .Values.rtlcore.values.RTL_DATA_BUS_PASSWORD }}'              
          resources:
            limits:
              cpu: "0.5"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 1Gi
          volumeMounts:
            - name: luk-auth-key-rsa-cm
              mountPath: /abc/app/goodt/task_org/key.rsa
              subPath: key.rsa
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      securityContext: {}
      imagePullSecrets:
        - name: gitlab-registry-vktech-secret
 
