apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rtlcore.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
      - name: port-8071-to-8071
        protocol: TCP
        port: 8071
        targetPort: 8071
  selector:
    app: {{ .Values.rtlcore.name }}
  type: ClusterIP
