apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-apps
  namespace: argocd #${argocd_namespace}
spec:
  generators:
  - git:
      repoURL: https://github.com/igyan2013/argocd-test-apps.git #${repo_project}
      revision: main #${branch}
      directories:
      - path: apps/*
      - path: apps/nginx3
        exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        name: apps
    spec:
      project: test-apps #${argocd_project}
      source:
        repoURL: https://github.com/igyan2013/argocd-test-apps.git  #${repo_project}
        targetRevision:  main #${branch}
        path: '*' #'infra/universal'
        helm:
          valueFiles:
          - /apps/{{path.basename}}/values.yaml
          - /apps/values.yaml
          - /main.yaml
      destination:
        name: in-cluster
        namespace: test-app #${app_namespace}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      ignoreDifferences:
      - group: apps
        kind: Deployment
        namespace: test-app #  ${app_namespace}
#        jqPathExpressions:
#        - .spec.template.spec.containers.[].env.[].valueFrom.resourceFieldRef.divisor
